Preserve exit status of the checksum command when verifying

diff --git a/rotcheck b/rotcheck
--- a/rotcheck
+++ b/rotcheck
@@ -163,19 +163,34 @@ printf_sanitized() {
     printf '\n'
 }
 
+verify_checksums() {
+    IGNORE="" ; [ $IGNORE_MISSING -eq 1 ]  && IGNORE="--ignore-missing"
+    WARN=""   ; [ $WARN_FORMATTING -eq 1 ] && WARN="-w"
+    $COMMAND -c $WARN $IGNORE -- "$CHECKFILE"
+}
+
 # Just verify checksums.
 if [ $CHECK_MODE -eq 1 ]; then
-    IGNORE="" ; [ $IGNORE_MISSING -eq 1 ] && IGNORE="--ignore-missing"
-    WARN="" ; [ $WARN_FORMATTING -eq 1 ] && WARN="-w"
-    if [ $QUIET -eq 1 ]; then
-        # Only the GNU coreutils checksum commands support the `--quiet`
-        # option, so use `grep -v` instead. Fortunately, the output format
-        # (at least for GNU coreutils and BusyBox) seems to be predictable.
-        $COMMAND -c $WARN $IGNORE -- "$CHECKFILE" | grep -Ev ': OK$'
+    # Only GNU coreutils supports `--quiet`, so use `grep -v` instead.
+    # Unfortunately, pipefail isn't POSIX so to return the exit status from the
+    # checksum command, we have to be clever (aka crazy) with file descriptors
+    # and subshells instead.
+    if [ $QUIET -eq 0 ]; then
+        verify_checksums
+        exit $?
     else
-        $COMMAND -c $WARN $IGNORE -- "$CHECKFILE"
+        exec 4>&1
+            (
+                exec 3>&1
+                    (
+                        # 2>&1 preserves order of stdout/stderr.
+                        verify_checksums 2>&1; printf '%d' $? 1>&3
+                    ) | grep -Ev ': OK$' 1>&4
+                exec 3>&-
+            ) | ( read -r retval; exit $retval ); retval=$?
+        exec 4>&-
+        exit $retval
     fi
-    exit $?
 fi
 
 # Delete checksums for files that no longer exist.
