Display more descriptive error if command not found

diff --git a/rotcheck b/rotcheck
--- a/rotcheck
+++ b/rotcheck
@@ -150,6 +150,12 @@ if [ $CHECK_MODE -eq 1 ] || [ $DELETE_MODE -eq 1 ]; then
     fi
 fi
 
+if ! command -v "$COMMAND" >/dev/null 2>/dev/null; then
+    fail "$COMMAND: not found" \
+         "Try installing GNU coreutils or BusyBox." \
+         "On *BSD, GNU coreutils commands begin with 'g', like 'gsha512sum'."
+fi
+
 # When printing text to terminal, make sure it won't do anything unexpected.
 printf_sanitized() {
     printf '%s' "$@" | tr -d '[:cntrl:]' | iconv -cs -f UTF-8 -t UTF-8
